version: '3'
services:
  app:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ~/workspace:/workspace
      - ~/.aws:/home/vscode/.aws
    environment:
      - TZ=Asia/Tokyo
